GET http://localhost:8080/secured/public
###
GET http://localhost:8080/secured/authenticated
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6Im1pY2hhZWxAamF2YS5hdCIsImdyb3VwcyI6WyJVc2VyIl0sImJpcnRoZGF0ZSI6IjIwMDEtMDEtMDEiLCJpYXQiOjE2NTMwNDcxODcsImV4cCI6MTY1MzEzMzU4NywianRpIjoiMzFiOGFhZTktMTkyNC00OTU5LTllZjMtZGE1MTM5ODhiMWFjIn0.O2uOlRl6YdSsX4CSUKjDwGzEcYE8WU8WHPo180V4-uWAuRlbS7LpievDzEpCTkiEs2LF2Lj2McuXCIEDCzcmaYFjrn75zanmWdCTbyn5Ldg55iXCXClxxSTowoaUt5bQMiTSBQZjzHOta8e6pQR7ofDGOVbMh7l8fDD8MympMMEjmGAIZjJNGKQwUfpuEqboxdNXZ3UBqrpRHa0ytpZxTLKY4krO3utI_mBKuyZdR-C7Ao0GnplfXqw9Wk-eHb8Hlm1TmxbdWrJL-o8CHHir71DvGHYGUgzU5wpqVcjAa2AzAhXfrxXpYnChp6ycguHJPhVy5QiaJPVx9UroNDZmDA


###
GET http://localhost:8080/secured/adminOnly
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6Im1pY2hhZWxAamF2YS5hdCIsImdyb3VwcyI6WyJVc2VyIl0sImJpcnRoZGF0ZSI6IjIwMDEtMDEtMDEiLCJpYXQiOjE2NTMwNDcxODcsImV4cCI6MTY1MzEzMzU4NywianRpIjoiMzFiOGFhZTktMTkyNC00OTU5LTllZjMtZGE1MTM5ODhiMWFjIn0.O2uOlRl6YdSsX4CSUKjDwGzEcYE8WU8WHPo180V4-uWAuRlbS7LpievDzEpCTkiEs2LF2Lj2McuXCIEDCzcmaYFjrn75zanmWdCTbyn5Ldg55iXCXClxxSTowoaUt5bQMiTSBQZjzHOta8e6pQR7ofDGOVbMh7l8fDD8MympMMEjmGAIZjJNGKQwUfpuEqboxdNXZ3UBqrpRHa0ytpZxTLKY4krO3utI_mBKuyZdR-C7Ao0GnplfXqw9Wk-eHb8Hlm1TmxbdWrJL-o8CHHir71DvGHYGUgzU5wpqVcjAa2AzAhXfrxXpYnChp6ycguHJPhVy5QiaJPVx9UroNDZmDA
