GET http://localhost:8080/secured/public
###
GET http://localhost:8080/secured/protected
### run test generate token, NOTE: token only valid a view minutes
GET http://localhost:8080/secured/protected
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6Impkb2VAcXVhcmt1cy5pbyIsImdyb3VwcyI6WyJVc2VyIiwiQWRtaW4iXSwiYmlydGhkYXRlIjoiMjAwMS0wNy0xMyIsImlhdCI6MTY1Mjc5NDQ5NiwiZXhwIjoxNjUyNzk0Nzk2LCJqdGkiOiJmY2JmOGQ3NS00YjY3LTRmY2UtOTBmOC05OTkxMjk2NGM3ZjkifQ.kZFip5rNYefUJXQ1M64WeoDX-I3TR-y_6_4zQDQzZYiL9RnMzPNPDVcX-vYYFUzU2kAxGr_HND2kb7FhWx7HRAD0UyxXB9X10Vh_2N1HVqrq6jtmr9q3hy0WgB2WyCNnCAN6aN1EgrJtTZ0wNTF-Qs3NeI82bEPwZFXPUg7GK2HGeSij4-bwSuaTlWDzHOp7REqSWRgj5aeCSg0vJufOUVh2zL-8DWffkTFNn6ruuvizc2YkKY443GK6ZT_3-2ahrQ5Z_3YNfaqAMmQLA7-IdsJzPHJjKifhZxgfSM8pzQzJKT9sbbTna_9n12j_7o9w02XzSH6jKdbQun9R4mgYrg


###
GET http://localhost:8080/secured/protected/groups
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6Impkb2VAcXVhcmt1cy5pbyIsImdyb3VwcyI6WyJVc2VyIiwiQWRtaW4iXSwiYmlydGhkYXRlIjoiMjAwMS0wNy0xMyIsImlhdCI6MTYzMjY0NDQzNiwiZXhwIjoxNjMyNjQ0NzM2LCJqdGkiOiJkMTE1M2ViOC0yYmMyLTRmZTEtODJhMi1mMDA2YTExMmJiZGIifQ.YLxwExwDKSnvuVIkgFt1FtJp3VvXdowsnFgYRy3DBW6fMJwYhtSVcuqeLwJgkjlUUNMwGe4bL7PJMTi5b91ObZDY1Yf7gccY4nlspy7mCn6KPmMOdqdbIc5CwEvWbN2MJM1KuqwFj7-e_5DlUZ20xVgA4VMxl-CBTjnHsmbt5TMMSRklwi93Tcgiix7uIrV_lgKETlADkoN7wwv_0BOiHzZKI7RuhZHrBq7prcNadOYotsbPpSPqjBpvI5Et9bCHDYNDvUGf8bX2RVj0QF5NbzaolMFa-H7tYaJQatmClIaWjIkxQSYkeWgw6Pcz2R9XTL-E4-oMo1d_aySvsMw4rQ

