GET http://localhost:8080/v3/customers
###
GET http://localhost:8080/v3/customers/2
### get non existing customer -> 404
GET http://localhost:8080/v3/customers/101
### create new customer
POST http://localhost:8080/v3/customers
Content-Type: application/json

{
  "name": "Michael Schaffler",
  "dateOfBirth": "1967-07-29",
  "status": "VIP"
}

### update customer
PUT http://localhost:8080/v3/customers/7
Content-Type: application/json

{
  "name": "Michael Schaffler",
  "dateOfBirth": "1967-07-29",
  "status": "VIP"
}

### delete customer
DELETE http://localhost:8080/v3/customers/7